name = "Create: Logistical Extreme"
author = "copygirl"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d01b987d626c340f12aa64d60718ce1685472d09ff07f6ae9e2b6c367b305a10"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
