name = "Create: Logistical Extreme"
author = "copygirl"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7442f0159d2a3db1b63f954035d7512cbf759c69c6643bf76048f4515d9d4ab6"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
