name = "Create: Logistical Extreme"
author = "copygirl"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbb877bcf3d1cfcc58997e5793b144842067da0c92b8301a6646abcf5be463cf"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
