# URL points to a folder where the modpack files
# are available along with the pack.toml file.
#url = "https://example.org/my_modpack"
# For testing locally using `packwiz serve`:
url = "http://localhost:8080"

# If set, changes the default memory allocation:
memory = 6144
